### ISSUE TITLE
Feat: Redux에 Upload 정보 추가

### ISSUE THREAD

**Issue by plutoin** [YOOJS1205/shine_masket#118]
도전 시작합니다......!

**Comment by YOOJS1205** [comment]
넵! 새로고침해도 redux의 state를 유지하려면 redux-persist를 사용해야하는데 사용이 안 되어서 테스트할때에는 localStorage에 담아야할 수도 있숩니다..!

**Comment by plutoin** [comment]
> 넵! 새로고침해도 redux의 state를 유지하려면 redux-persist를 사용해야하는데 사용이 안 되어서 테스트할때에는 localStorage에 담아야할 수도 있숩니다..!

헉 역시 리덕스 너무너무 어렵네요............ 준상님 말씀 참고해서 해보겠습니다!!!!!!!
