### ISSUE TITLE
Fix: 상단 검색창 기본 표시 변경

### ISSUE THREAD

**Issue by ryungom** [YOOJS1205/shine_masket#124]
삼항연산자를 잘못 넣었더니 모든 페이지에서 검색창이 나오는 치명(?)적인 버그를 발견해서 우선적으로 먼저 수정합니다...ㅎㅎ

**Comment by YOOJS1205** [comment]
ㅋㅋㅋㅋ 깜짝 놀랬네요 넵 !!
