### ISSUE TITLE
Refactor: 상단 메뉴 컴포넌트 수정

### ISSUE THREAD

**Issue by YOOJS1205** [YOOJS1205/shine_masket#62]
현재 상단 메뉴 컴포넌트가
<img width="201" alt="image" src="https://user-images.githubusercontent.com/89122773/177799844-e4a0fd2d-7891-47cf-b370-f7f1f869db0b.png">
다음과 같이 세트로 되어있어서 저장 버튼을 빼고 오른쪽에는 자유롭게 추가할 수 있도록 수정하겠습니다!

**Comment by hhnssl** [comment]
뽜이팅~!
