### ISSUE TITLE
Refactor: 버튼에 IR요소 별도 추가

### ISSUE THREAD

**Issue by ryungom** [YOOJS1205/shine_masket#91]
이미지 들어가더라도, alt값을 추가 하지 않더라도 IR기법이 설명 가능토록 한번 코드를 살짝 추가해보겠습니다

**Comment by YOOJS1205** [comment]
감사합니다!! 혹시 제가 버튼 태그 자체에 alt값을 부여해서 생긴 문제가 맞나요?

**Comment by ryungom** [comment]
준상님의 버튼 해결로 인하여 이슈 닫음~!
